POST http://localhost:3000/api/v1/customers/2/address
Content-Type: application/json
Cookie: sessionId=a76b3444-f8a5-4ced-a264-f1c85618778c; Max-Age=864; Path=/; Expires=Tue, 30 May 2023 08:05:31 GMT; HttpOnly

{
    "city": "Sofia",
    "country": "Bulgaria",
    "streetName": "Main",
    "streetNumber": 62,
    "postalCode": 1000,
    "addressNumber": 1
}

###

PUT http://localhost:3000/api/v1/customers/1/details
Content-Type: application/json
Cookie: sessionId=2649e854-ecb3-4d0c-bcaf-7876f561cf1b; Max-Age=864; Path=/; Expires=Mon, 29 May 2023 16:01:45 GMT; HttpOnly

{
    "firstName": "Pesho",
    "lastName": "Petrov",
    "phoneNumber": "088444155"
}

###

PATCH http://localhost:3000/api/v1/customers/1/password
Content-Type: application/json
Cookie: sessionId=1fb281be-0c22-46d7-885f-1cc2c8436b56; Max-Age=864; Path=/; Expires=Tue, 30 May 2023 07:41:09 GMT; HttpOnly

{
    "oldPassword": "Pesho123",
    "newPassword": "Krisko123"
}

###

DELETE http://localhost:3000/api/v1/customers/1
Content-Type: application/json
Cookie: sessionId=1fb281be-0c22-46d7-885f-1cc2c8436b56; Max-Age=864; Path=/; Expires=Tue, 30 May 2023 07:41:09 GMT; HttpOnly

{
    "password": "Krisko123",
    "deleteMessage": "DELETE"
}