GET http://localhost:3000/api/v1/products?sortOrder=price ASC
Content-Type: application/json
Cookie: sessionId=550a70a8-6034-432d-a6b0-f410487ad528; Max-Age=864; Path=/; Expires=Mon, 03 Jul 2023 08:10:12 GMT; HttpOnly

###

GET http://localhost:3000/api/v1/products/1
Content-Type: application/json
Cookie: sessionId=550a70a8-6034-432d-a6b0-f410487ad528; Max-Age=864; Path=/; Expires=Mon, 03 Jul 2023 08:10:12 GMT; HttpOnly

###

POST http://localhost:3000/api/v1/products
Content-Type: application/json
Cookie: sessionId=550a70a8-6034-432d-a6b0-f410487ad528; Max-Age=864; Path=/; Expires=Mon, 03 Jul 2023 08:10:12 GMT; HttpOnly

{
    "name": "T-Shirt",
    "description": "Best product",
    "price": 10,
    "promotionId": 2,
    "categoryId": 3,
    "inStock": 3,
    "isActive": true
}

###

PUT http://localhost:3000/api/v1/products/41
Content-Type: application/json
Cookie: sessionId=550a70a8-6034-432d-a6b0-f410487ad528; Max-Age=864; Path=/; Expires=Mon, 03 Jul 2023 08:10:12 GMT; HttpOnly

{
    "inStock": 20
}

