POST http://localhost:3000/api/v1/promotions
Content-Type: application/json
Cookie: sessionId=904d50df-df1b-47ae-9e59-bee610948952; Max-Age=864; Path=/; Expires=Sun, 02 Jul 2023 08:56:43 GMT; HttpOnly

{
    "title": "Best promotion",
    "description": "One of the best",
    "discountRate": 30,
    "startDate": "2022-01-01",
    "endDate": "2024-10-10"
}

###

PUT http://localhost:3000/api/v1/promotions/4
Content-Type: application/json
Cookie: sessionId=1515bce4-f082-44a0-adce-2c6e66c95b92; Max-Age=864; Path=/; Expires=Wed, 14 Jun 2023 07:51:42 GMT; HttpOnly

{
    "title": "Best Best",
    "description": "One of the best",
    "discountRate": 30
}

###

DELETE http://localhost:3000/api/v1/promotions/3
Content-Type: application/json
Cookie: sessionId=f581171b-5dfa-4c66-a304-19fbef81805d; Max-Age=864; Path=/; Expires=Wed, 07 Jun 2023 09:36:17 GMT; HttpOnly

###

GET http://localhost:3000/api/v1/promotions/2
Content-Type: application/json
Cookie: sessionId=f581171b-5dfa-4c66-a304-19fbef81805d; Max-Age=864; Path=/; Expires=Wed, 07 Jun 2023 09:36:17 GMT; HttpOnly

###

GET http://localhost:3000/api/v1/promotions
Content-Type: application/json
Cookie: sessionId=f581171b-5dfa-4c66-a304-19fbef81805d; Max-Age=864; Path=/; Expires=Wed, 07 Jun 2023 09:36:17 GMT; HttpOnly
